### ISSUE TITLE
Package not found on bower

### ISSUE THREAD

**Issue by ashtonian** [loringdodge/ionic-ion-tinder-cards-2#1]
```
bower install ionic-tinder-cards-2 
```

The above seems to fail with package not found - I ended up installing directly: 

```
bower install https://github.com/loringdodge/ionic-ion-tinder-cards-2.git
```

Ace plugin BTW! Thanks!

**Comment by loringdodge** [comment]
It has been added! You can now use `bower install ionic-tinder-cards-2` to install. Thanks for the notification.

**Comment by ashtonian** [comment]
Closing this as it was resolved a long time ago - thanks again :)
