### ISSUE TITLE
Dynamically swipe left/right or discard

### ISSUE THREAD

**Issue by AdrienDC** [loringdodge/ionic-ion-tinder-cards-2#2]
Hi @loringdodge ,
I'm currently implementing your fork and really appreciate it but I was wondering how to programtically swipe or discard a card, from a button for example.

**Comment by loringdodge** [comment]
Hey @AdrienDC,

I believe what you're looking for is already part of the included functionality. Check out this [Codepen](http://codepen.io/loringdodge/pen/BNmRrK?editors=101). There's a function attached to scope called `onClickTransitionOut(card)` where card is the card object supplied from the iterator (ng-repeat). Additionally, `onClickTransitionOut` dispatches an event using $emit called 'removeCard' and in your parent controller, you can define what should occur. 

Here's how to include it in your template (pulled from the Codepen example):

```
<div class="discard" ng-click="onClickTransitionOut(card)">DISCARD</div>
```

And here's how you would listen on the event that is emitted. This specific function pushes the removed card to the discards pile. However, you could change that to whichever you like.

```
$scope.$on('removeCard', function(event, element, card) {
    var discarded = $scope.cards.master.splice($scope.cards.master.indexOf(card), 1);
    $scope.cards.discards.push(discarded);
   // or $scope.cards.liked.push(discarded);
 });
```

Hope that helps, or if it doesn't, let me know more in depth what you're attempting to achieve.

**Comment by AdrienDC** [comment]
Thanks Loring, yes in fact I used this event to simulate a left swipe and quickly added the same behavior for the right side. Thanks for your great work anyway :)

**Comment by loringdodge** [comment]
@AdrienDC 

Awesome. Glad that you got it working!

**Comment by andrewoodleyjr** [comment]
@AdrienDC @loringdodge 
Can you provide a demonstration of how to do this from within the controller?

**Comment by loringdodge** [comment]
Hey @andrewoodleyjr 

The only place where you'll have access to the onClickTransitionOut within a controller is in the CardCtrl.

```
      <div ng-if="cards.active">
        <td-cards>
          <td-card ng-repeat="card in cards.active">
            <div class="image" ng-controller="CardCtrl">
                 // ...your custom card template
            </div>
          </td-card>
        </td-cards>
      </div>
```

The above is an example of a template where td-cards is being iterated on by an ng-repeat and invoking a new instance of a CardCtrl. You'll need to define a new CardCtrl instance but on that scope should be the onClickTransitionOut method that will discard that specific card. 

```
.controller('CardCtrl', function($scope, TDCardDelegate) {
    console.log($scope.onClickTransitionOut) // I am a defined function
});
```

Hope that helps!

**Comment by cortezcristian** [comment]
Still can't achive the swipe right with this lib.

What if I want to achieve with a couple of buttons that are not in the card scope?

Like this demo:
http://codepen.io/julienroubieu/pen/mJeJJE?editors=1010

I end up doing somethig ugly like this in the `CardCtrl` and triggering the clicks from outside

```
  $scope.onClickTransitionRight = function($event, card){
     $scope.$parent.swipeCard.width = 1000;
     $scope.$parent.swipeCard.x = 1;
     // wish i can modify targetX: 1000
     $scope.$parent.swipeCard.animateFlyAway({gesture: { deltaX : -400, deltaY: 400, 
                   velocityX: 0.1, targetX: 1000 }});
  }

  $scope.onClickTransitionLeft = function($event, card){
    $scope.$parent.swipeCard.onClickTransitionOut();
  }
```

**Comment by klahaeck** [comment]
I am having the same issue with trying to programmatically swipe cards from outside the directives entirely. I'd like to have separate buttons that trigger either a swipe to the left or right without using any swipe gestures. I've tried to follow the same methods as the "discard" example but that click event is within the scope of the individual cards.

**Comment by cortezcristian** [comment]
@klahaeck  I did acomplished that with the shared code snippet

**Comment by klahaeck** [comment]
@cortezcristian how did you trigger the clicks from outside of `CardsCtrl` and `CardCtrl`?

**Comment by klahaeck** [comment]
@cortezcristian nevermind, got it figured out. Thanks!

**Comment by craze3** [comment]
Can someone please explain how to add buttons outside the ng-repeat loop that are able to call onClickTransitionOut for the top card? I'm new to angular & having a really hard time..
@klahaeck @cortezcristian

**Comment by kuzdogan** [comment]
I'm not really sure how I've managed it as I'm a newbie in AngularJS but this code works. Change the animateFlyAway function as below:

```
animateFlyAway: function(e) {

      // is animation triggered by drag or click?
      //var draggable = (e !== undefined);

       var self = this;

            var isGestureSwipe = (typeof e === "object");
            var swipeRight = isGestureSwipe ? this.x > 0 : e === "right";

      self.updateIndex();

      self.onTransitionOut(self.thresholdAmount);

            var angle, targetX, targetY, velocityX, rotateTo;

            if (swipeRight) {
                targetX = (this.parentWidth / 2) + (this.width);
            } else {
                targetX = -(this.parentWidth + this.width);
            }

            if (isGestureSwipe) {
                angle = Math.atan(e.gesture.deltaX / e.gesture.deltaY);
                // Target Y is just the "opposite" side of the triangle of targetX as the adjacent edge (sohcahtoa yo)
                targetY = targetX / Math.tan(angle);
                velocityX = e.gesture.velocityX;
                rotateTo = this.rotationAngle;
            } else {
                angle = -1.5;
                targetY = 100;
                velocityX = 0.5;
                rotateTo = -0.2;
            }
            this.thresholdAmount = this.thresholdAmount || 0;

            var duration = 0.3 - Math.min(Math.max(Math.abs(velocityX) / 10, 0.05), 0.2);

            ionic.requestAnimationFrame(function() {
                self.el.style.transform = self.el.style.webkitTransform = 'translate3d(' + targetX + 'px, ' + targetY + 'px,0) rotate(' + rotateTo + 'rad)';
                self.el.style.transition = self.el.style.webkitTransition = 'all ' + duration + 's ease-in-out';
            });
```

Change onClickTransitionOut(card) to two different functions

```
    controller: ['$scope', '$element', function($scope, $element) {
        // Emits event 'dislikeCard' which should have a listener in a parent scope
        $scope.$parent.onClickTransitionLeft = function(card) {
          var element = $scope.$parent.swipeCard;
          element.onClickTransitionLeft();
          $scope.$emit('dislikeCard', element, card);
        },
        $scope.$parent.onClickTransitionRight = function(card) {
          var element = $scope.$parent.swipeCard;
          element.onClickTransitionRight();
          $scope.$emit('likeCard', element, card);
        }
      }],
```

in app.js I've changed 'removeCard' event functions to 'dislikeCard' and 'likeCard':

```
  $scope.$on('dislikeCard', function(event, element, card) {
    var disliked = $scope.cards.active.splice($scope.cards.master.indexOf(card), 1);
    $scope.cards.disliked.push(disliked);
  });

  $scope.$on('likeCard', function(event, element, card) {
    var liked = $scope.cards.active.splice($scope.cards.master.indexOf(card), 1);
    $scope.cards.liked.push(liked);
  });
```

You can call functions in HTML as following:

```
<div class="left" ng-click="onClickTransitionLeft(card)">Left</div>
<div class="right" ng-click="onClickTransitionRight(card)">Right</div>
```

**Comment by kevincobain2000** [comment]
will try it, thanks

**Comment by ghost** [comment]
Hi. I'm new to AngularJS and I'am having some trouble trying to swipe the cards from outside the ng-repeat. I've already tried the @kuzdogan example but I think something's missing in my solution, because the 'card' parameter is always set for the last card in the cards array. Could you please provide an example in codepen?
