### ISSUE TITLE
Desactivate draging feature on other layer cards

### ISSUE THREAD

**Issue by AdrienDC** [loringdodge/ionic-ion-tinder-cards-2#4]
Hi,
Is that possible to deactivate the drag for other layers than the first one. This in order to avoid weird behavior if the user didn't put his finger exactly on the first card but a bit below... It would be a nice improvment! Thanks!

**Comment by loringdodge** [comment]
@AdrienDC 

I see what you mean and I would definitely agree with you. If I have the opportunity over the next couple of weeks, I'll look into implementing this feature.

**Comment by AdrienDC** [comment]
Thanks a lot Loring, it's would be awesome ! 
HNY

**Comment by loringdodge** [comment]
Hey @AdrienDC,

Just wanted to let you know that I updated the module to not allow dragging unless it's the first card. You can check out the example [codepen](http://codepen.io/loringdodge/pen/BNmRrK).

**Comment by AdrienDC** [comment]
Thank you so much @loringdodge , it works like a charm !
