### ISSUE TITLE
Animation Problem

### ISSUE THREAD

**Issue by cfontana0** [loringdodge/ionic-ion-tinder-cards-2#6]
Hello, I'm having the following problem:
https://gyazo.com/ca3128dd58d074253ff4f38a79860680

It looks like the z-index of the elements is not correct, besides, I don't know why the deleted card is back again to the center of the page.

Thanks!

**Comment by loringdodge** [comment]
Hey @cfontana0 

That is a very interesting problem! Can you describe the environment that you're working in (browser, ios, android)? And if the problem persists in all three? Also, I think we can resolve this issue but maybe you could send me a code example?

Thanks,
Loring

**Comment by cfontana0** [comment]
Hey Loring, thanks for your reply.
I can reproduce the error with all the environments (browser, ios, android).

I did a temporal fix to this problem, but it is not the best solution.
I'm hiding all the cards, except for the active one. Besides, I'm hiding the active one after the swipe event, so, I don't see when the card is back again.
Check it out: https://i.gyazo.com/0abacac1346dcd8fca281bcf8ed5ee92.gif

This is my code:
`<td-cards>
                      <div ng-repeat="card in cards.active">
                      <td-card on-destroy="cardDestroyed($index)" on-swipe-left="cardSwipedLeft($index)" on-swipe-right="cardSwipedRight($index)" class="ng-hide" ng-hide="card.hide">
                        <div class="image card-detail center">
                            <div class="no-text">NO</div>
                            <div class="square">
                                  <div class="count">{{card.number}}/{{::data.cards.length}}</div>
                                  <img ng-src="{{card.image}}" ng-show="card.image"/>
                                  <div class="spacer" style="height: 100px;" ng-hide="card.image"></div>
                                  <div class="title">{{card.text}}</div>
                                  <div class="spacer" style="height: 80px;" ng-hide="card.image"></div>
                                  <div class="card-credit">
                                      <span class="ok-button"><center>CREDITS</center></span>
                                      <span class="credits">+{{::card.credits}}</span>
                                  </div>
                            </div>
                            <div class="yes-text">YES</div>
                        </div>
                      </td-card>
                    </td-cards>`

`.controller('dataValidationCtrl', function($scope, $state, $timeout, $api, $rootScope, $ionicLoading, $errorHandler, TDCardDelegate) {
    var cardsCount, successCallback, answerQuestion, next;

```
if ($rootScope.profile === undefined) {
    $state.go('login');
    return;
}

$scope.go = function (view) {
    $state.go(view);
    if (view !== 'logout') {
        $state.go(view);
    } else {
        $ionicPopup.show({
            title: ' Are you sure you want to log out?', cssClass: 'logout-popup',
            buttons: [{text: 'Cancel'}, {text: 'Logout', onTap: function(e) {$state.go('logout');}}]
        });
    }
};

$scope.data = {};

successCallback = function (questions) {
    var qNumber = 1;
    $scope.data.cards = [];

    angular.forEach(questions, function(question, key) {
        if (question.type === 'yesOrNo') {
            question.number = qNumber;
            question.position = (qNumber<5)?5*(qNumber+1):20;
            question.hide = true;
            this.push(question);
            qNumber++;
        }
    }, $scope.data.cards);

    cardsCount = $scope.data.cards.length;

    $scope.cards = {
        master: Array.prototype.slice.call($scope.data.cards, 0),
        active: Array.prototype.slice.call($scope.data.cards, 0),
        discards: [],
        liked: [],
        disliked: []
    }

    $scope.cards.active[0].hide = false;

    $ionicLoading.hide();
    $scope.ready = true;
};

$ionicLoading.show();
$scope.ready = false;

$api.getUnansweredQuestions({'owner': $rootScope.profile._id}, successCallback, $errorHandler);

answerQuestion = function(card) {
    var data = {};
    data.owner = $rootScope.profile._id;
    data['with.id'] = card._id;
    data['with.type'] = 'question';

    $api.userInteractions(data).then(function(interactions) {
        var interaction = interactions[0];

        if (!interaction) {
            return;
        }

        if (card.status === 'later') {
            interaction.skippedDate = (new Date()).toString();
        } else {
            interaction.completedDate = (new Date()).toString();
            if (!interaction.meta) {
                interaction.meta = {};
            }
            interaction.meta.text = card.status;
        }

        $api.model('user_interaction').update(interaction);
    });
};

$scope.cardDestroyed = function(index) {
    $scope.cards.active[index+1].hide = false;
    $scope.cards.active.splice(index, 1);
};

$scope.$on('removeCard', function(event, element, card) {
    var discarded = $scope.cards.master.splice($scope.cards.master.indexOf(card), 1);
    $scope.cards.discards.push(discarded);
});

$scope.cardSwipedLeft = function(index) {
    var card = $scope.cards.active[index];
    var nextCard = $scope.cards.active[$scope.cards.active.indexOf(card)+1];
    card.hide = true;

    card.status = 'no';
    answerQuestion(card);

    if (nextCard === undefined) {
        $state.go('main');
        return
    }
};
$scope.cardSwipedRight = function(index) {
    var card = $scope.cards.active[index];
    var nextCard = $scope.cards.active[$scope.cards.active.indexOf(card)+1];
    card.hide = true;

    card.status = 'yes';
    answerQuestion(card);

    if (nextCard === undefined) {
        $state.go('main');
        return
    }
};

$scope.buttonClick = function (card, onClickTransitionOut, response) {
    var nextCard = $scope.cards.active[$scope.cards.active.indexOf(card)+1];

    card.status = response;
    answerQuestion(card);

    if (nextCard === undefined) {
        $state.go('main');
        return
    }

    onClickTransitionOut(card);
};
```

})`

Thanks,
Carlos

**Comment by loringdodge** [comment]
@cfontana0 

I took a look at your code and I think ng-if may fix the problem. The td-cards directive requires that the object being iterated on being available whenever its compiled and linked. If it's not there, things get goofy. Try this and let me know if it works.

```
<div ng-if="cards.active">
   <td-cards ng-repeat="card in cards.active">
     ....
  </td-cards>
</div>
```

**Comment by cfontana0** [comment]
Hey @loringdodge thanks for your answer.
I implemented the code that you indicated me, and it fixed part of the problem.
Check it out: https://gyazo.com/2acda22898ada7bbb513ec2c312232ca

I still can see the card going back to the center. is it weird?

I'm using the following JS libraries:
lib/collide/collide.js
lib/ionic/js/ionic.bundle.js
lib/ionic-service-core/ionic-core.js
lib/ngCordova/dist/ng-cordova.min.js
lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js
lib/ng-lodash/build/ng-lodash.min.js
lib/angular-youtube-mb/dist/angular-youtube-embed.min.js
http://static.intercomcdn.com/intercom.v1.js
lib/ionic-tinder-cards-2/ionic.tdcards2.js

Best regards,
Carlos

**Comment by loringdodge** [comment]
@cfontana0 

I'm glad that this solved part of the problem and I do see that the animation flashes back toward the center on swipe. Unfortunately, I'm unsure was to how to resolve this problem without seeing the source code. Do you think you could reproduce the problem in a Codepen or Plunkr, etc.? Then I could more property diagnose the problem. 

If you don't have the opportunity, a recommendation to do on your own might be to implement the tinder cards [Codepen](http://codepen.io/loringdodge/pen/BNmRrK) example in your app to run as a baseline to narrow the scope of the issue and add code from there.

**Comment by cfontana0** [comment]
Hey @loringdodge thanks!

I fixed the problem. I created a **directive** that hides the **card** on the "**dragend**" event.

```
.directive('tinder', function ($ionicGesture) {
    return {
        link: function(scope, element, attrs) {
            $ionicGesture.on('dragend', function(event) {
              element[0].style.display = 'none';
            }, element);
        }
    };
})
```

Thanks for your help.

Regards,
Carlos
